/* Customer's Canvas Website — interactive Phase 1 CJM prototype.
   Static content and simulated conversion forms; no lead data is transmitted. */
(function(){
"use strict";
var app=document.getElementById("app");
var routesSeen=[];
var capabilities=[
{id:"flows",title:"Offer Flexible Personalization Flows",short:"Give every customer the right way to personalize.",icon:"✳",headline:"Let customers personalize products their way.",lead:"Offer guided template editing, artwork upload, freeform design, product configuration, variable data, and mixed workflows without forcing every buyer through the same experience.",problem:"A designer uploading finished artwork should not have to use the same ordering interface as an office manager editing a business card.",items:["Template editing with protected content and brand rules","Customer artwork upload with validation","Freeform editors and product option configuration","Hybrid journeys, bundles and variable data personalization"],outcomes:["Match the ordering experience to the customer, product and channel.","Help buyers complete orders without unnecessary back-and-forth.","Keep approved templates and reusable assets in the workflow."],related:["production","orders","integration"],solutions:["print-service-providers","business-printing","promo-products","direct-mail"],steps:["Choose the right personalization method","Capture or create customer artwork","Carry the design into the next order step"],faq:[["Does every product need an online designer?","No. Buyers can use templates, upload finished files, configure options or follow combined workflows, depending on the product and business process."],["Can flows be embedded in our own application?","Customer's Canvas Hub provides editors and APIs for integrated experiences. Portal offers a ready-to-configure ordering environment."],["Does the platform support personalized batches?","Variable-data scenarios can populate templates from structured data, with rendering and production preparation configured for the intended workflow."]]},
{id:"production",title:"Turn Designs into Production-Ready Files",short:"Move from customer artwork to usable production output.",icon:"▧",headline:"Take customer artwork from design to production-ready output.",lead:"Handle artwork checks, rendering, output settings and production file generation as part of the digital order journey, with the level of automation your process needs.",problem:"A good-looking preview is not necessarily a usable production file. The handoff needs predictable dimensions, bleed, color handling, resolution and format.",items:["Preflight and feedback on submitted artwork","Production-oriented rendering and configurable output","PDF and image outputs, including variable-data files","Imposition, layout and specialized output where configured"],outcomes:["Reduce repetitive file preparation and manual corrections.","Make output more consistent with product requirements.","Connect customized artwork to the existing production process."],related:["flows","orders","integration"],solutions:["print-service-providers","packaging","large-format","direct-mail"],steps:["Validate incoming design data","Generate output for the product specification","Hand files to downstream production systems"],faq:[["Does this replace our complete prepress department or RIP?","No. The focus is artwork intake, validation, rendering and preparation for production handoff. Existing RIP, imposition and specialist prepress tools can remain part of the workflow."],["Can customers upload finished designs?","Yes. Artwork submission is one of the supported personalization paths and can include checks before production handoff."],["What production formats are available?","Formats and output options depend on the configured capability and scenario. Exact specifications should be reviewed for each implementation."]]},
{id:"orders",title:"Keep Orders Moving from Intake to Production",short:"Connect intake, approvals and production handoff.",icon:"↗",headline:"Move complex print orders forward, without losing the context.",lead:"Connect customer submissions, artwork, approvals, status changes and production handoff in a more coherent ordering journey.",problem:"Complex orders often get stuck between emails, files, account managers and disconnected applications.",items:["Order capture and tracking within supported workflows","Approval and proofing steps","Status synchronization, notifications and routing","Bulk ordering, reorder and post-submission updates"],outcomes:["Keep order context attached to the job.","Reduce manual coordination across customer-facing steps.","Connect accepted work to the systems already running production."],related:["flows","production","integration"],solutions:["print-service-providers","business-printing","marketing-services","direct-mail"],steps:["Capture an order and artwork","Route through required checks and approvals","Update status and hand off to production"],faq:[["Does Customer's Canvas replace our MIS or ERP?","No. Portal provides ordering workflows and Hub exposes capabilities to integrate into existing systems. Detailed order lifecycle ownership is implementation-specific."],["Can we include approvals?","Approval and proofing stages can be part of configured order workflows."],["Can buyers reorder saved products?","Reorder and saved-design scenarios are among the personalization and order capabilities; availability varies by implementation."]]},
{id:"integration",title:"Integrate With Your Systems",short:"Work with your storefront, software and production stack.",icon:"⌘",headline:"Connect personalization with the systems you already rely on.",lead:"Integrate product configuration, editing, artwork rendering and orders with existing storefronts, portals, business systems and production workflows.",problem:"The personalization experience is only one piece of the order. Product data, customers, payments, jobs and production often live elsewhere.",items:["APIs and SDKs for embeddable experiences","Connectors and integration patterns for ecommerce","Data and asset exchange with existing business systems","Webhooks and delivery pipelines for downstream processing"],outcomes:["Avoid rebuilding software that already works.","Choose between a ready-to-go Portal and an embedded Hub approach.","Keep the customer experience connected across ordering and production."],related:["flows","orders","production"],solutions:["software-vendors","print-service-providers","marketing-services","packaging"],steps:["Map the systems and owners","Choose Portal or Hub integration points","Connect and validate the operational handoff"],faq:[["Do we need to replace our existing storefront?","Not if you choose an embedded approach with Hub. Portal is an alternative for teams who prefer a ready-to-go ordering environment."],["Does Portal also support integration?","Yes. Portal can be connected to external business and production systems, with the exact integration determined by the use case."],["Are APIs available?","Hub provides developer-facing APIs and SDKs; implementation details and available components are described in the technical documentation."]]}
];
var products=[
{id:"portal",title:"Customer's Canvas Portal",tag:"Ready-to-go solution",icon:"▣",headline:"Launch a better B2B print ordering experience.",lead:"A ready-to-configure portal for print service providers and organizations that need branded ordering, controlled personalization and a path from customer order to production.",problem:"You need a digital sales channel, but you don't want to build the ordering experience and customization stack from scratch.",items:["B2B ordering environment and customer-facing product catalog","Template personalization and artwork submission","Order flows and approval options","Integration with existing business and production systems"],outcomes:["Start with a ready-to-go ordering experience rather than a custom frontend.","Give customers a simpler path to recurring, branded and complex orders.","Extend the workflow to meet your operational requirements."],audience:"Print service providers, in-plant teams and organizations launching a customer-facing print portal.",use:["print-service-providers","business-printing","marketing-services"],cap:["flows","orders","production","integration"],faq:[["Is Portal a standalone website for ordering?","Portal is intended as a ready-to-go ordering environment that can be configured for the business and connected to other systems."],["Can it connect to our MIS or ERP?","Integration is part of the implementation approach. Exact data exchanges, status ownership and connector requirements must be scoped."],["Can we see it before a call?","Yes. The shared Online Demo shows a representative personalization and ordering experience. Additional scenarios can be discussed with the team."]]},
{id:"hub",title:"Customer's Canvas Hub",tag:"Embed & build",icon:"⌘",headline:"Add personalization to the software you already run.",lead:"Editors, APIs and rendering infrastructure to bring customer-facing customization, data-driven personalization and production-oriented output into an existing storefront, portal or application.",problem:"You already have a product, ordering flow or platform. Building and maintaining the personalization stack yourself would distract from your core business.",items:["Embeddable editors and controlled templates","APIs and SDKs for personalization scenarios","Rendering and variable-data generation","Integration-oriented workflows and output delivery"],outcomes:["Keep your existing application and customer experience.","Adopt only the personalization capabilities you need.","Connect previews, artwork and output to your own process."],audience:"Software vendors, ecommerce teams, direct mail platforms and businesses with an existing application or engineering capability.",use:["software-vendors","direct-mail","promo-products"],cap:["flows","production","integration","orders"],faq:[["Is Hub a full web-to-print storefront?","No. Hub provides platform services and embeddable components. Your application or connected products provide the broader customer experience."],["Do we have to use all Hub components?","No. Teams can select capabilities based on their use case and integration architecture."],["Is technical documentation available?","Yes. The existing public technical documentation remains accessible independently from this website prototype."]]}
];
var solutions=[
{id:"print-service-providers",title:"Print Service Providers",icon:"▧",headline:"Bring more print orders online, even when they are complex.",lead:"Give commercial and specialty print customers a self-service way to configure products, personalize or upload artwork, approve proofs and send usable data into production.",problem:"Too many jobs still arrive by email, with scattered files and manual follow-up.",items:["Customer portals for repeat and B2B ordering","Template editing plus print-file submission","Approvals, production output and MIS handoff"],outcomes:["Move recurring orders out of inboxes.","Spend less time clarifying artwork and specifications.","Give trade and direct customers more control."],recommend:"portal",secondary:"hub",caps:["flows","orders","production","integration"],other:["business-printing","large-format","packaging"],faq:[["Can we start without replacing our MIS?","Yes. The intended approach is to integrate ordering and personalization with your existing production software."],["Is Portal or Hub better for a print business?","Portal is a natural starting point for a ready-to-go ordering channel. Hub suits teams building or extending their own application."]]},
{id:"marketing-services",title:"Marketing Services",icon:"◈",headline:"Make branded marketing material easier to order and personalize.",lead:"Support teams, clients and distributed locations with approved templates, controlled changes and repeatable ordering workflows for print and campaign materials.",problem:"Local teams need autonomy, while agencies and brand owners need control over layouts, assets and output.",items:["Brand-safe templates for distributed users","Data-driven personalization for campaigns","Approval paths and connected artwork production"],outcomes:["Reduce one-off design requests.","Keep branded materials more consistent.","Make recurring campaign assets faster to prepare."],recommend:"portal",secondary:"hub",caps:["flows","orders","production"],other:["direct-mail","business-printing","software-vendors"],faq:[["Can users customize approved brand templates?","Controlled template editing can restrict what may be changed and preserve fixed design elements."],["Can this replace a campaign management platform?","No. Customer's Canvas focuses on personalization, artwork and connected ordering workflows rather than the full marketing automation stack."]]},
{id:"software-vendors",title:"Software Vendors & Platforms",icon:"⌘",headline:"Add print personalization without rebuilding its infrastructure.",lead:"Embed editors, template workflows and rendering in software your customers already use, including print MIS, ecommerce products and marketing platforms.",problem:"Customers request print customization, but creating a robust design and rendering stack inside your SaaS product is expensive to maintain.",items:["Embeddable editing components and APIs","Template and variable-data workflows","Rendering, previews and file handoff"],outcomes:["Extend your product without maintaining a separate print engine.","Keep the user inside your platform.","Choose the integration points that suit your architecture."],recommend:"hub",secondary:"portal",caps:["integration","flows","production"],other:["direct-mail","marketing-services","print-service-providers"],faq:[["Can Hub be embedded in our UI?","Yes. Hub is intended for integrated workflows and provides APIs and embeddable components."],["Does Hub take over customer accounts or payments?","Not by default. Your application can remain responsible for business processes outside the selected personalization capabilities."]]},
{id:"business-printing",title:"Business Printing",icon:"▤",headline:"Make repeat business print orders simple and consistent.",lead:"Let teams personalize approved stationery and business materials while retaining control of branding, access and output specifications.",problem:"Repeat orders of business cards, stationery and collateral involve small edits but unnecessary design and approval effort.",items:["Editable branded templates and product catalogs","Business cards, stationery and collateral ordering","Brand governance and repeat order flows"],outcomes:["Reduce time spent on routine changes.","Avoid off-brand designs.","Give distributed teams a consistent ordering channel."],recommend:"portal",secondary:"hub",caps:["flows","orders","production"],other:["marketing-services","print-service-providers","promo-products"],faq:[["Can employees order their own materials?","Controlled personalization is designed for scenarios where approved templates are reused by different users or teams."],["Is the artwork production-ready?","Output requirements depend on the configured print product and production pipeline."]]},
{id:"direct-mail",title:"Direct Mail",icon:"✉",headline:"Add self-service personalization to direct mail workflows.",lead:"Offer campaign setup, approved templates, variable data and production-file generation as part of your customer experience or existing platform.",problem:"Campaign data, creative templates and production processes often live in separate systems, leaving manual work between them.",items:["Customer-facing templates for direct mail pieces","Variable text, images, codes and data mapping","Batch rendering and output into fulfillment flows"],outcomes:["Help customers launch repeat campaigns more easily.","Reduce repetitive composition work.","Keep data-driven print connected to the channel you operate."],recommend:"hub",secondary:"portal",caps:["flows","production","integration","orders"],other:["marketing-services","software-vendors","print-service-providers"],faq:[["Is this a full direct mail marketing platform?","No. Customer's Canvas provides personalization, template editing and rendering capabilities that can connect to campaign and fulfillment systems."],["Can data populate templates in batches?","Variable data personalization supports mapping structured input to templates for rendering." ]]},
{id:"packaging",title:"Packaging",icon:"⬡",headline:"Simplify custom packaging artwork and ordering.",lead:"Support packaging and label buyers with suitable customization and file-submission experiences, connected to the production specifications and systems you use.",problem:"Packaging jobs combine artwork, dimensions, dielines and specialized output requirements that generic product editors do not cover well.",items:["Product-specific personalization and customer artwork upload","Artwork checks and production-oriented output","Integration into packaging business workflows"],outcomes:["Clarify artwork requirements earlier.","Reduce back-and-forth on submitted design files.","Connect personalized items to the production process."],recommend:"hub",secondary:"portal",caps:["flows","production","integration"],other:["print-service-providers","promo-products","large-format"],faq:[["Does it generate any FEFCO box style automatically?","This prototype does not claim universal FEFCO/ECMA generation. Specific structure, dieline and output requirements should be validated for a proposed implementation."],["Can buyers upload their own artwork?","Yes. Artwork submission and checking are supported personalization scenarios." ]]},
{id:"large-format",title:"Large Format",icon:"▥",headline:"Make wide-format customization easier to order.",lead:"Help customers specify size, materials and artwork for signage, displays and large-format products, then connect the request to production.",problem:"Large dimensions, nonstandard products and varied customer files make manual quoting and artwork intake costly.",items:["Product option selection and custom dimensions","Upload, previews and artwork checks","Configurable output and workflow integration"],outcomes:["Capture more complete customer requirements.","Reduce avoidable artwork questions.","Support complex products without generic one-size-fits-all flows."],recommend:"portal",secondary:"hub",caps:["flows","production","orders"],other:["print-service-providers","promo-products","packaging"],faq:[["Can products have different dimensions and options?","Product-attribute configuration is among the supported personalization paths; constraints depend on the product setup."],["Does it replace existing production software?","No. The intent is to connect the customer-facing workflow with the systems used for production."]]},
{id:"promo-products",title:"Promotional Products",icon:"◉",headline:"Let buyers see and personalize the product they want.",lead:"Bring logo placement, product options and visual previews into an ordering experience for branded merchandise and promotional items.",problem:"Buyers need confidence about how a logo or design will look on a product, and suppliers need usable artwork and options.",items:["Product-specific customization and selectable options","Visual previews and mockups","Approval-friendly artwork and downstream output"],outcomes:["Help customers make decisions with better previews.","Collect required details during ordering.","Keep customization connected to production or fulfillment."],recommend:"portal",secondary:"hub",caps:["flows","production","integration"],other:["large-format","business-printing","print-service-providers"],faq:[["Can customers add logos to products?","Product-specific editors and personalization flows support customer asset placement where configured."],["Is a preview the same as a final print file?","No. Preview and production output are separate parts of the process, with different configuration requirements."]]}
];
var capMap=Object.fromEntries(capabilities.map(function(x){return [x.id,x];}));
var prodMap=Object.fromEntries(products.map(function(x){return [x.id,x];}));
var solMap=Object.fromEntries(solutions.map(function(x){return [x.id,x];}));
function e(str){return String(str==null?"":str).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function path(type,id){return "#/"+type+"/"+id;}
function aLink(url,text,cls){return '<a class="'+(cls||"inline-link")+'" href="'+e(url)+'">'+e(text)+'</a>';}
function bullets(items){return '<ul class="list">'+items.map(function(x){return "<li>"+e(x)+"</li>";}).join("")+"</ul>";}
function icon(sym,variation){return '<span class="card-icon '+(variation||"")+'">'+e(sym)+'</span>';}
function arrow(){return '<span class="arrow">Explore <span aria-hidden="true">↗</span></span>';}
function homeArt(){return '<div class="art" aria-label="Illustration of personalized design moving into a customer order"><div class="art-bg"></div><div class="art-stage"><div class="art-top"><i></i><i></i><i></i></div><div class="art-body"><div class="art-side"><div class="sidebar-line"></div><div class="sidebar-chip"></div><div class="sidebar-chip"></div><div class="sidebar-chip"></div></div><div class="art-main"><div class="paper"><div class="paper-label">YOUR BRAND</div><div class="paper-title">Make it<br>yours.</div><div class="paper-shape"></div><div class="paper-line"></div><div class="paper-line short"></div></div></div></div></div><div class="art-float float-a"><span>✦</span> Personalize online</div><div class="art-float float-b"><span>✓</span> Artwork checked</div><div class="art-float float-c"><span>↗</span> Ready for production</div></div>';}
function illustration(title,steps){return '<div class="illustration-card"><div class="illus-caption">'+e(title)+'</div><div class="flow-visual">'+steps.map(function(s,i){return '<div class="flow-row"><i>'+("0"+(i+1))+'</i>'+e(s)+'</div>';}).join("")+'</div></div>';}
function card(url,ico,title,description,tag){return '<a class="card" href="'+e(url)+'">'+icon(ico,tag==="Integration"?"mint":tag==="Solution"?"gold":"")+'<h3>'+e(title)+'</h3><p>'+e(description)+'</p>'+arrow()+'</a>';}
function sectionHead(kicker,title,lead){return '<div class="section-header"><div><div class="kicker">'+e(kicker)+'</div><h2>'+e(title)+'</h2>'+(lead?'<p>'+e(lead)+'</p>':"")+'</div></div>';}
function ctaBand(title,text,primaryUrl,primaryText){return '<section class="section-tight"><div class="container"><div class="band"><div><h2>'+e(title)+'</h2><p>'+e(text)+'</p></div>'+aLink(primaryUrl,primaryText,'btn btn-light')+'</div></div></section>';}
function faqBlock(faq){if(!faq||!faq.length)return "";return '<section class="section section-soft"><div class="container"><div class="faq"><div><div class="kicker">FAQs</div><h2>Questions you may have</h2><p class="body-copy">A quick answer before you explore the demo or talk to the team.</p></div><div class="faq-list">'+faq.map(function(q){return '<details><summary>'+e(q[0])+'</summary><p>'+e(q[1])+'</p></details>';}).join("")+'</div></div></div></section>';}
function benefits(items){return items.map(function(x,i){return '<div class="benefit"><div class="benefit-dot">✓</div><div><strong>'+e(x)+'</strong></div></div>';}).join("");}
function breadcrumbs(group,title){return '<div class="container"><div class="breadcrumb"><a href="#/">Home</a><span>›</span><span>'+e(group)+'</span><span>›</span><strong>'+e(title)+'</strong></div></div>';}
function pageHero(group,tag,headline,lead,graphicLabel,graphicSteps){return '<header class="page-hero">'+breadcrumbs(group,tag)+'<div class="container page-hero-layout"><div><div class="eyebrow">'+e(group)+' · '+e(tag)+'</div><h1>'+e(headline)+'</h1><p>'+e(lead)+'</p><div class="hero-buttons">'+aLink("#/demo","Try Online Demo","btn btn-primary")+aLink("#/contact","Talk to our team","btn btn-outline")+'</div></div>'+illustration(graphicLabel,graphicSteps)+'</div></header>';}
function sectionCards(title,lead,items){return '<section class="section section-soft"><div class="container">'+sectionHead("Explore further",title,lead)+'<div class="grid grid-3">'+items.join("")+'</div></div></section>';}
function home(){
 var productCards=products.map(function(p){return '<a class="card product-card" href="'+path("products",p.id)+'"><div class="product-top '+p.id+'"><span class="tag">'+e(p.tag)+'</span><div class="product-ui"><div class="ui-head"></div><div class="ui-block"></div><div class="ui-row"><b></b><b></b><b></b></div></div></div><div class="product-body"><h3>'+e(p.title)+'</h3><p>'+e(p.lead)+'</p><span class="arrow">Explore '+(p.id==="portal"?"Portal":"Hub")+' ↗</span></div></a>';}).join("");
 var solCards=solutions.slice(0,6).map(function(s){return card(path("solutions",s.id),s.icon,s.title,s.lead,"Solution");}).join("");
 var capCards=capabilities.map(function(c){return card(path("capabilities",c.id),c.icon,c.title,c.short,"Capability");}).join("");
 return '<section class="hero"><div class="container hero-inner"><div><div class="eyebrow">Personalization infrastructure for print & commerce</div><h1>Better ways to order, personalize and produce.</h1><p class="hero-lead">Customer’s Canvas brings customer-facing personalization, artwork handling and production workflows together. Launch a ready-to-go portal or bring the capabilities into software you already use.</p><div class="hero-buttons">'+aLink("#/products/portal","Explore Portal","btn btn-primary")+aLink("#/products/hub","Explore Hub","btn btn-outline")+'</div><div class="hero-note">Not another disconnected editor. A practical path from customer artwork to production.</div></div>'+homeArt()+'</div></section>'+
 '<section class="section"><div class="container">'+sectionHead("Two ways to get started","Choose what fits your business.","Use a ready-to-go ordering environment or add personalization to your existing application.")+'<div class="grid grid-2">'+productCards+'</div></div></section>'+
 '<section class="section section-soft"><div class="container">'+sectionHead("Your customer journey","From ordering challenge to working solution.","Follow a path based on your business, then explore the capabilities and see an example in action.")+'<div class="path-cards"><div class="path-step"><span class="num">STEP 01</span><h3>Find your scenario</h3><p>Commercial print, direct mail, packaging, enterprise print and more.</p>'+aLink("#/solutions/print-service-providers","Browse solutions ↗","inline-link")+'</div><div class="path-step"><span class="num">STEP 02</span><h3>See what’s possible</h3><p>Explore flexible personalization, artwork output, order flows and integration.</p>'+aLink("#/capabilities/flows","Explore capabilities ↗","inline-link")+'</div><div class="path-step"><span class="num">STEP 03</span><h3>Validate the fit</h3><p>Try a customer-facing example, then discuss the specifics of your workflow.</p>'+aLink("#/demo","Try Online Demo ↗","inline-link")+'</div></div></div></section>'+
 '<section class="section"><div class="container">'+sectionHead("Solutions","Built around the work you do.","Start with a business problem, not an internal product architecture.")+'<div class="grid grid-3">'+solCards+'</div><div style="margin-top:24px">'+aLink("#/solutions","See all solutions →","btn btn-outline")+'</div></div></section>'+
 '<section class="section section-soft"><div class="container">'+sectionHead("Capabilities","More than the editor.","The customer experience works when artwork, approvals, output and integrations work together.")+'<div class="grid grid-2">'+capCards+'</div></div></section>'+
 '<section class="section"><div class="container"><div class="two-column"><div><div class="kicker">Bring it into your workflow</div><h2>Built to work with your systems, not around them.</h2><p class="body-copy">Whether you launch with Portal or embed Hub, the goal is a connected ordering and personalization experience that fits your existing operations.</p><div class="hero-buttons">'+aLink("#/capabilities/integration","Explore integrations","btn btn-primary")+aLink("#/contact","Talk to our team","btn btn-outline")+'</div></div>'+illustration("Connected journey",["Customer-facing ordering","Artwork and approval","Production systems"])+'</div></div></section>'+
 faqBlock([["Is Customer's Canvas a web-to-print storefront or a platform?","Both approaches are available. Portal offers a ready-to-go ordering environment; Hub offers editors, APIs and rendering components for use in an existing application."],["Can we keep our current production software?","Yes. The website narrative is built around integrating the personalization and order journey with existing business and production systems."],["Can we try the product without speaking to Sales?","The Online Demo is intended to be self-service. This prototype simulates its email gate and leads to the existing demo experience."]])+
 ctaBand("See the customer journey in action.","Explore personalization and ordering before committing to an implementation conversation.","#/demo","Try Online Demo →");
}
function productPage(p){
 var related=p.use.map(function(id){var s=solMap[id];return card(path("solutions",id),s.icon,s.title,s.lead,"Solution");});
 var capCards=p.cap.map(function(id){var c=capMap[id];return card(path("capabilities",id),c.icon,c.title,c.short,"Capability");});
 var other=products.find(function(x){return x.id!==p.id;});
 return pageHero("Products",p.title,p.headline,p.lead,p.tag,[p.id==="portal"?"Configure branded portal":"Keep your existing application",p.id==="portal"?"Customers personalize and order":"Embed editors and APIs","Connect output and operations"])+
 '<section class="section"><div class="container two-column"><div><div class="kicker">Where it fits</div><h2>'+e(p.problem)+'</h2><p class="body-copy">'+e(p.audience)+'</p></div><div class="highlight-panel"><h3>What you can build with '+e(p.title)+'</h3>'+bullets(p.items)+'</div></div></section>'+
 '<section class="section section-soft"><div class="container">'+sectionHead("Business value","Get the right foundation for your ordering experience.","Choose the level of product and engineering responsibility that makes sense for you.")+'<div class="grid grid-3">'+p.outcomes.map(function(x){return '<div class="card">'+icon("✓","mint")+'<h3>'+e(x)+'</h3></div>';}).join("")+'</div></div></section>'+
 sectionCards("Capabilities that make it work","Follow the underlying building blocks.",capCards)+
 '<section class="section"><div class="container">'+sectionHead("Common use cases","See where it fits.","Explore businesses and ordering situations that use these capabilities.")+'<div class="grid grid-3">'+related.join("")+'</div></div></section>'+
 '<section class="section section-soft"><div class="container two-column"><div><div class="kicker">Compare your options</div><h2>Need a different starting point?</h2><p class="body-copy">Portal and Hub solve related needs in different ways. The right choice depends on what you already run, your resources, and the ownership of the customer-facing workflow.</p></div><div class="highlight-panel"><span class="tag">'+e(other.tag)+'</span><h3 style="margin-top:15px">'+e(other.title)+'</h3><p>'+e(other.lead)+'</p>'+aLink(path("products",other.id),"Compare with "+other.title+" ↗","inline-link")+'</div></div></section>'+
 faqBlock(p.faq)+ctaBand("Let's map it to your workflow.","Explore an online example or talk through your products, systems and requirements.","#/demo","Try Online Demo →");
}
function solutionPage(s){
 var cCards=s.caps.map(function(id){var c=capMap[id];return card(path("capabilities",id),c.icon,c.title,c.short,"Capability");});
 var other=s.other.map(function(id){var a=solMap[id];return card(path("solutions",id),a.icon,a.title,a.lead,"Solution");});
 var rec=prodMap[s.recommend],alt=prodMap[s.secondary];
 return pageHero("Solutions",s.title,s.headline,s.lead,"A connected path",["Customer selects and personalizes","Artwork, checks and approvals","Files and order data to production"])+
 '<section class="section"><div class="container two-column"><div><div class="kicker">The challenge</div><h2>'+e(s.problem)+'</h2><p class="body-copy">Customer’s Canvas addresses the personalization and artwork-handling parts of the journey while connecting them to the systems used for other business and production processes.</p></div><div class="highlight-panel"><h3>What this workflow can include</h3>'+bullets(s.items)+'</div></div></section>'+
 '<section class="section section-soft"><div class="container">'+sectionHead("What changes","Make the ordering experience easier to run.","Focus on the steps that create the most friction in your current workflow.")+'<div class="grid grid-3">'+s.outcomes.map(function(x){return '<div class="card">'+icon("✓","mint")+'<h3>'+e(x)+'</h3></div>';}).join("")+'</div></div></section>'+
 '<section class="section"><div class="container">'+sectionHead("Capabilities","See what supports this solution.","A connected solution is made from the capabilities you actually need.")+'<div class="grid grid-2">'+cCards.join("")+'</div></div></section>'+
 '<section class="section section-soft"><div class="container two-column"><div><div class="kicker">How to start</div><h2>Pick the delivery model that fits.</h2><p class="body-copy">These are suggested starting points, not a substitute for checking the actual requirements and supported functionality.</p></div><div><div class="card" style="margin-bottom:14px"><span class="tag">Suggested first look</span><h3>'+e(rec.title)+'</h3><p>'+e(rec.lead)+'</p>'+aLink(path("products",rec.id),"Explore "+rec.title+" ↗","inline-link")+'</div><div class="card"><h3>Also consider '+e(alt.title)+'</h3><p>'+e(alt.lead)+'</p>'+aLink(path("products",alt.id),"See the alternative ↗","inline-link")+'</div></div></div></section>'+
 sectionCards("Related business scenarios","If your needs cross more than one area.",other)+faqBlock(s.faq)+
 ctaBand("See how the pieces come together.","Test an online personalization scenario before discussing the specifics of your business.","#/demo","Try Online Demo →");
}
function capabilityPage(c){
 var related=c.related.map(function(id){var x=capMap[id];return card(path("capabilities",id),x.icon,x.title,x.short,"Capability");});
 var solutionCards=c.solutions.slice(0,3).map(function(id){var s=solMap[id];return card(path("solutions",id),s.icon,s.title,s.lead,"Solution");});
 return pageHero("Capabilities",c.title,c.headline,c.lead,"How it connects",c.steps)+
 '<section class="section"><div class="container two-column"><div><div class="kicker">The problem</div><h2>'+e(c.problem)+'</h2><p class="body-copy">Use the capability where it improves a specific step; the surrounding order, payment and production systems can remain in place.</p></div><div class="highlight-panel"><h3>Relevant functionality</h3>'+bullets(c.items)+'</div></div></section>'+
 '<section class="section section-soft"><div class="container">'+sectionHead("Why it matters","Build a more dependable customer journey.","Use targeted capabilities to remove the manual work between steps.")+'<div class="grid grid-3">'+c.outcomes.map(function(x){return '<div class="card">'+icon("✓","mint")+'<h3>'+e(x)+'</h3></div>';}).join("")+'</div></div></section>'+
 '<section class="section"><div class="container">'+sectionHead("Fit and delivery","Available through two approaches.","Portal and Hub are different ways to use Customer’s Canvas capabilities. The exact functional scope depends on implementation.")+'<div class="grid grid-2">'+products.map(function(p){return card(path("products",p.id),p.icon,p.title,p.id==="portal"?"Start with a ready-to-configure ordering portal.":"Embed selected capabilities into your own platform.","Product");}).join("")+'</div></div></section>'+
 sectionCards("Connected capabilities","The other pieces of the workflow.",related)+
 '<section class="section"><div class="container">'+sectionHead("Used for","See it in a business context.","Follow these examples to find your own use case.")+'<div class="grid grid-3">'+solutionCards.join("")+'</div></div></section>'+
 faqBlock(c.faq)+ctaBand("Explore it from the buyer's side.","The interactive demo provides a concrete example of customer-facing customization and ordering.","#/demo","Try Online Demo →");
}
function catalogue(type){
 var list=type==="solutions"?solutions:capabilities;
 return '<section class="page-hero">'+breadcrumbs("Explore",type==="solutions"?"Solutions":"Capabilities")+'<div class="container" style="padding-top:38px;padding-bottom:40px"><div class="eyebrow">'+e(type)+'</div><h1>'+ (type==="solutions"?"Find the right path for your business.":"Capabilities that connect the journey.")+'</h1><p class="hero-lead">'+(type==="solutions"?"Browse common business scenarios, see a suggested starting point, then explore the underlying capabilities.":"Move beyond a standalone editor. Explore personalization flows, artwork production, order operations and integration.")+'</p></div></section>'+
 '<section class="section"><div class="container"><div class="grid grid-3">'+list.map(function(x){return card(path(type,x.id),x.icon,x.title,type==="solutions"?x.lead:x.short,type);}).join("")+'</div></div></section>'+
 ctaBand("Not sure where to start?","We can map your current workflow and recommend the right approach.","#/contact","Talk to our team →");
}
function demo(){
 return '<section class="page-hero">'+breadcrumbs("Explore","Online Demo")+'<div class="container" style="padding:35px 0 65px"><div class="eyebrow">See it for yourself</div><h1>Try a personalization experience online.</h1><p class="hero-lead">Explore a representative customer-facing journey powered by Customer’s Canvas. The example runs on Portal technology and demonstrates capabilities also available for integration through Hub.</p></div></section>'+
 '<section class="section demo-shell"><div class="container"><div class="demo-gate"><div class="demo-info"><div class="eyebrow" style="color:#a4f1e0">What you can explore</div><h2>A real workflow is easier to judge than a feature list.</h2>'+bullets(["Product selection and personalization","Customer-facing editing and previews","A representative online ordering journey"])+'<div class="callout-note" style="background:#ffffff1b;color:#d5e4ff">Prototype note: this page simulates the planned work-email gate. It does not store or send contact details.</div></div><form class="demo-form" id="demo-form"><div class="kicker">Explore the experience</div><h3>Open the Online Demo</h3><p class="body-copy">In the live website, entering a work email will provide immediate access, with no email confirmation step.</p><div class="field"><label for="demo-email">Work email</label><input id="demo-email" name="email" type="email" autocomplete="email" required placeholder="you@company.com"></div><label class="consent"><input type="checkbox" required><span>I understand this is an interactive prototype; this form will not transmit my email.</span></label><button class="btn btn-primary" type="submit">Continue to demo →</button><div id="demo-response" role="status" aria-live="polite"></div><p class="form-footnote">Live demo destination: portal-public.customerscanvas.com. The real lead capture and CRM handoff are out of scope for this prototype.</p></form></div></div></section>'+
 '<section class="section section-soft"><div class="container">'+sectionHead("Continue exploring","What should you investigate next?","A demo answers what the user experience looks like. Products and capabilities explain how to implement it.")+'<div class="grid grid-3">'+card("#/products/portal","▣","Launch with Portal","A ready-to-configure ordering environment.","Product")+card("#/products/hub","⌘","Build with Hub","Add personalization to the software you already run.","Product")+card("#/capabilities/flows","✳","Personalization flows","See the different ways customers create or provide artwork.","Capability")+'</div></div></section>';
}
function contact(){
return '<section class="page-hero">'+breadcrumbs("Company","Talk to our team")+'<div class="container" style="padding:35px 0 55px"><div class="eyebrow">Discovery conversation</div><h1>Let us map Customer’s Canvas to your workflow.</h1><p class="hero-lead">Tell us what you sell and where ordering, artwork or integration currently becomes difficult.</p></div></section>'+
'<section class="section"><div class="container two-column"><div><div class="kicker">What we can clarify</div><h2>Start with the practical questions.</h2>'+bullets(["Where Portal or Hub fits the current architecture","How customers submit or create artwork","How approvals and production output connect","What to validate in a technical evaluation"])+'<div class="callout-note">Prototype note: the form does not send any information. Use it to evaluate whether the invitation and next steps make sense.</div></div><form id="contact-form" class="highlight-panel"><h3>Request a discovery conversation</h3><div class="field"><label for="c-name">Your name</label><input id="c-name" name="name" required placeholder="Full name"></div><div class="field"><label for="c-email">Work email</label><input id="c-email" name="email" type="email" required placeholder="you@company.com"></div><div class="field"><label for="c-company">Company</label><input id="c-company" name="company" required placeholder="Company name"></div><div class="field"><label for="c-context">What would you like to improve?</label><input id="c-context" name="context" placeholder="Ordering, artwork, integration…"></div><label class="consent"><input type="checkbox" required><span>This is a simulated form. My information will not be sent or stored.</span></label><button class="btn btn-primary" type="submit">Request conversation →</button><div id="contact-response" role="status" aria-live="polite"></div></form></div></section>';
}
function megaItem(url,title,desc,ico){return '<a href="'+e(url)+'" class="mega-link"><span class="mega-icon">'+e(ico)+'</span><span><strong>'+e(title)+'</strong><span>'+e(desc)+'</span></span></a>';}
function menu(){
 return '<div class="protop"><div class="container"><span><span class="proto-dot"></span><strong>Phase 1 prototype</strong> <span class="proto-description">· Explore the navigation, content and conversion journeys</span></span><span class="badge-small">Concept / not live</span></div></div>'+
 '<header class="header"><div class="container header-inner"><a class="brand" href="#/" aria-label="Customer’s Canvas homepage"><span class="brand-mark">◈</span><span>Customer’s Canvas</span></a>'+
 '<nav class="nav" id="site-nav" aria-label="Main navigation">'+
 '<details class="nav-drop"><summary>Products <span class="nav-chevron">⌄</span></summary><div class="mega"><div class="mega-section-title">How do you want to use it?</div>'+products.map(function(p){return megaItem(path("products",p.id),p.title,p.id==="portal"?"Launch a ready-to-go portal":"Embed capabilities into your own system",p.icon);}).join("")+'</div></details>'+
 '<details class="nav-drop wide"><summary>Solutions <span class="nav-chevron">⌄</span></summary><div class="mega"><div class="mega-section-title">Find your business scenario</div><div class="mega-grid">'+solutions.map(function(s){return megaItem(path("solutions",s.id),s.title,"Explore the use case",s.icon);}).join("")+'</div><div style="padding:12px 8px 0">'+aLink("#/solutions","View all solutions →","inline-link")+'</div></div></details>'+
 '<details class="nav-drop wide"><summary>Capabilities <span class="nav-chevron">⌄</span></summary><div class="mega"><div class="mega-section-title">What the platform helps you do</div><div class="mega-grid">'+capabilities.map(function(c){return megaItem(path("capabilities",c.id),c.title,c.short,c.icon);}).join("")+'</div><div style="padding:12px 8px 0">'+aLink("#/capabilities","View all capabilities →","inline-link")+'</div></div></details>'+
 '<details class="nav-drop"><summary>Resources <span class="nav-chevron">⌄</span></summary><div class="mega"><div class="mega-section-title">Existing resources (live website)</div>'+megaItem("https://customerscanvas.com/case-studies","Case studies","Customer stories","◉")+megaItem("https://customerscanvas.com/blog","Blog","Articles and guides","▤")+megaItem("https://customerscanvas.com/docs","Documentation","Public guides and APIs","⌘")+'</div></details>'+
 '<a class="nav-static" href="https://customerscanvas.com/company">Company</a>'+
 '</nav><div class="nav-actions">'+aLink("#/contact","Contact sales","text-btn")+aLink("#/demo","Try Online Demo","btn btn-primary btn-small")+'<button class="mobile-menu" type="button" id="mobile-menu" aria-expanded="false" aria-controls="site-nav" aria-label="Toggle navigation">☰</button></div></div></header>';
}
function footer(){
var link=function(url,name){return aLink(url,name,"footer-link");};
return '<footer class="footer"><div class="container"><div class="footer-grid"><div><a href="#/" class="brand"><span class="brand-mark">◈</span> Customer’s Canvas</a><p>Personalization, ordering and artwork workflows for print and commerce.</p><span class="tag" style="background:#2a3a57;color:#aecaf4">Interactive prototype</span></div><div><h4>Products</h4>'+products.map(function(p){return link(path("products",p.id),p.title);}).join("")+'</div><div><h4>Solutions</h4>'+solutions.slice(0,6).map(function(s){return link(path("solutions",s.id),s.title);}).join("")+link("#/solutions","All solutions")+'</div><div><h4>Capabilities</h4>'+capabilities.map(function(c){return link(path("capabilities",c.id),c.title);}).join("")+'</div><div><h4>Explore</h4>'+link("#/demo","Online Demo")+link("#/contact","Contact sales")+link("https://customerscanvas.com/docs","Documentation")+link("https://customerscanvas.com/case-studies","Case studies")+'</div></div><div class="footer-bottom"><span>Customer’s Canvas © 2026. Prototype for internal review; not a published product claim.</span><span>Phase 1 IA · Navigation · Customer journey</span></div></div></footer>';
}
function journeyPanel(){
return '<div class="journey"><div class="journey-pane" id="journey-pane"><h3>Test a customer journey</h3><p>Follow a path and look for missing context, weak connections or unclear next steps.</p>'+
'<button type="button" class="journey-case" data-journey="printer"><strong>Commercial printer</strong><span>Solution → Portal → Capability → Demo</span></button>'+
'<button type="button" class="journey-case" data-journey="platform"><strong>Software platform</strong><span>Solution → Hub → Integration → Demo</span></button>'+
'<button type="button" class="journey-case" data-journey="marketing"><strong>Marketing services</strong><span>Solution → Personalization → Demo</span></button>'+
'<div class="journey-route" id="journey-route">Visited pages: —</div><button type="button" class="pill" style="margin-top:12px" id="reset-journey">Reset path</button></div><button type="button" class="journey-toggle" id="journey-toggle" aria-expanded="false">◎ Test a journey <span>↑</span></button></div>';
}
function notFound(){return '<section class="section"><div class="container"><h1>Page not found</h1><p>This route is not part of the Phase 1 prototype.</p>'+aLink("#/","Return to homepage","btn btn-primary")+'</div></section>';}
function pageType(route){var parts=route.split("/").filter(Boolean);if(parts.length===0)return "Home";if(parts[0]==="products"&&prodMap[parts[1]])return prodMap[parts[1]].title;if(parts[0]==="solutions"&&solMap[parts[1]])return solMap[parts[1]].title;if(parts[0]==="capabilities"&&capMap[parts[1]])return capMap[parts[1]].title;if(parts[0]==="demo")return "Online Demo";if(parts[0]==="contact")return "Contact sales";return parts[0];}
function getRoute(){var raw=(location.hash||"#/").slice(1);return raw[0]==="/"?raw:"/"+raw;}
function render(){
 var current=getRoute(),parts=current.split("/").filter(Boolean),page;
 if(parts.length===0)page=home();
 else if(parts[0]==="products"&&prodMap[parts[1]])page=productPage(prodMap[parts[1]]);
 else if(parts[0]==="solutions"&&parts.length===1)page=catalogue("solutions");
 else if(parts[0]==="solutions"&&solMap[parts[1]])page=solutionPage(solMap[parts[1]]);
 else if(parts[0]==="capabilities"&&parts.length===1)page=catalogue("capabilities");
 else if(parts[0]==="capabilities"&&capMap[parts[1]])page=capabilityPage(capMap[parts[1]]);
 else if(parts[0]==="demo")page=demo();
 else if(parts[0]==="contact")page=contact();
 else page=notFound();
 app.innerHTML=menu()+'<main id="main-content">'+page+'</main>'+footer()+journeyPanel();
 var name=pageType(current);document.title=(name==="Home"?"Customer's Canvas":name+" | Customer's Canvas")+" — Phase 1 Prototype";
 if(routesSeen[routesSeen.length-1]!==name){routesSeen.push(name);if(routesSeen.length>12)routesSeen.shift();}
 var routePanel=document.getElementById("journey-route");
 if(routePanel)routePanel.textContent="Visited pages: "+routesSeen.join(" → ");
 window.scrollTo({top:0,behavior:"instant"});
 var all=document.querySelectorAll(".nav-drop");all.forEach(function(d){d.addEventListener("toggle",function(){if(d.open)all.forEach(function(other){if(other!==d)other.open=false;});});});
 var menuButton=document.getElementById("mobile-menu");menuButton.addEventListener("click",function(){var nav=document.getElementById("site-nav");var open=nav.classList.toggle("is-open");menuButton.setAttribute("aria-expanded",String(open));});
 var form=document.getElementById("demo-form");if(form)form.addEventListener("submit",function(ev){ev.preventDefault();document.getElementById("demo-response").innerHTML='<div class="notice"><strong>Prototype step completed.</strong><br>No email was saved or transmitted. In the real site, this would create a Demo lead and open the experience immediately.<div style="margin-top:14px">'+aLink("https://portal-public.customerscanvas.com/","Open live Demo →","btn btn-primary btn-small")+'</div></div>';});
 var contactForm=document.getElementById("contact-form");if(contactForm)contactForm.addEventListener("submit",function(ev){ev.preventDefault();document.getElementById("contact-response").innerHTML='<div class="notice"><strong>Simulated request received.</strong> Nothing was sent or stored. The real form would create a Contact Sales lead with context.</div>';});
 document.getElementById("journey-toggle").addEventListener("click",function(){var el=document.getElementById("journey-pane");var open=el.classList.toggle("open");this.setAttribute("aria-expanded",String(open));});
 document.getElementById("reset-journey").addEventListener("click",function(){routesSeen=[];document.getElementById("journey-route").textContent="Visited pages: —";});
 document.querySelectorAll("[data-journey]").forEach(function(button){button.addEventListener("click",function(){var persona=this.getAttribute("data-journey");routesSeen=[];var urls={printer:"#/solutions/print-service-providers",platform:"#/solutions/software-vendors",marketing:"#/solutions/marketing-services"};location.hash=urls[persona];if(location.hash===urls[persona])render();});});
}
window.addEventListener("hashchange",render);
render();
})();